# Generated by Django 5.2.17 on 2026-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_sub', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('remaining', models.PositiveIntegerField()),
                ('image_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-created_at'],
            },
        ),
    ]
